# Generated by Django 5.2.13 on 2026-04-15 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0003_imovel_imagem_principal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImovelImagem',
            fields=[
                ('id_imagem', models.AutoField(primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='imoveis/galeria/')),
                ('ordem', models.PositiveSmallIntegerField(default=0)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('id_imovel', models.ForeignKey(db_column='id_imovel', on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='imovel.imovel')),
            ],
            options={
                'verbose_name': 'Imagem do Imóvel',
                'verbose_name_plural': 'Imagens do Imóvel',
                'db_table': 'imovel_imagem',
                'ordering': ['ordem', 'id_imagem'],
            },
        ),
    ]
