# Generated by Django 5.2.13 on 2026-04-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0005_favorito'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='contador_cliques',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
