# Generated by Django 5.2.13 on 2026-04-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imovel', '0006_imovel_contador_cliques'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilutilizador',
            name='receber_notificacoes_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilutilizador',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
